/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.Cliente;
import modelo.Puesto;
import modelo.Empleado;
import javax.swing.JOptionPane;
/**
 *
 * @author DELL
 */
public class frm_clientes extends javax.swing.JFrame {
Cliente cliente = new Cliente();
Puesto puesto = new Puesto();
Empleado empleado = new Empleado();
    /**
     * Creates new form frm_clientes
     */
    public frm_clientes() {
        initComponents();
        cliente = new Cliente();
        this.tbl_datos_clientes.setModel(cliente.leer());
        puesto = new Puesto();
        this.tbl_datos_puestos.setModel(puesto.leerPuestos());
        empleado = new Empleado();
        this.tbl_datos_empleados.setModel(empleado.leer());
        empleado.rellenarComboBox("puestos", "puesto", cb_puestos);
    }
    
    // Método para limpiar los campos de la tabla de clientes
    private void limpia_datos_clientes(){
        lbl_resultado_id_clientes.setText("");
        txt_nit_clientes.setText("");
        txt_nombres_clientes.setText("");
        txt_apellidos_clientes.setText("");
        txt_direccion_clientes.setText("");
        txt_telefono_clientes.setText("");
        txt_fn_clientes.setText("");
    }
    
    // Método para limpiar los campos de la tabla de puestos
    private void limpia_datos_puestos(){
        lbl_resultado_id_puestos.setText("");
        txt_puestos.setText("");
    }
    
    // Método para limpiar los campos de la tabla de empleados
    private void limpia_datos_empleados(){
        lbl_resultado_id_empleados.setText("");
        txt_codigo_empleados.setText("");
        txt_nombres_empleados.setText("");
        txt_apellidos_empleados.setText("");
        txt_direccion_empleados.setText("");
        txt_telefono_empleados.setText("");
        txt_fn_empleados.setText("");
        cb_puestos.setSelectedIndex(0);
    }
    
    // Método para seleccionar datos de la tabla de clientes
    private void select_datos_clientes() {
        int fila = tbl_datos_clientes.getSelectedRow();
        lbl_resultado_id_clientes.setText(tbl_datos_clientes.getValueAt(fila, 0).toString());
        txt_nit_clientes.setText(tbl_datos_clientes.getValueAt(fila, 1).toString());
        txt_nombres_clientes.setText(tbl_datos_clientes.getValueAt(fila, 2).toString());
        txt_apellidos_clientes.setText(tbl_datos_clientes.getValueAt(fila, 3).toString());
        txt_direccion_clientes.setText(tbl_datos_clientes.getValueAt(fila, 4).toString());
        txt_telefono_clientes.setText(tbl_datos_clientes.getValueAt(fila, 5).toString());
        txt_fn_clientes.setText(tbl_datos_clientes.getValueAt(fila, 6).toString());
    }

    // Método para seleccionar datos de la tabla de puestos
    private void select_datos_puestos() {
        int fila = tbl_datos_puestos.getSelectedRow();
        lbl_resultado_id_puestos.setText(tbl_datos_puestos.getValueAt(fila, 0).toString());
        txt_puestos.setText(tbl_datos_puestos.getValueAt(fila, 1).toString());
    }
    
    // Método para seleccionar datos de la tabla de empleados
    private void select_datos_empleados() {
        int fila = tbl_datos_empleados.getSelectedRow();
            lbl_resultado_id_empleados.setText(tbl_datos_empleados.getValueAt(fila, 0).toString());
            txt_codigo_empleados.setText(tbl_datos_empleados.getValueAt(fila, 1).toString());
            txt_nombres_empleados.setText(tbl_datos_empleados.getValueAt(fila, 2).toString());
            txt_apellidos_empleados.setText(tbl_datos_empleados.getValueAt(fila, 3).toString());
            txt_direccion_empleados.setText(tbl_datos_empleados.getValueAt(fila, 4).toString());
            txt_telefono_empleados.setText(tbl_datos_empleados.getValueAt(fila, 5).toString());
            txt_fn_empleados.setText(tbl_datos_empleados.getValueAt(fila, 6).toString());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_principal = new javax.swing.JTabbedPane();
        jp_clientes = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_nit_clientes = new javax.swing.JLabel();
        txt_nit_clientes = new javax.swing.JTextField();
        lbl_nombres_clientes = new javax.swing.JLabel();
        txt_nombres_clientes = new javax.swing.JTextField();
        lbl_apellidos_clientes = new javax.swing.JLabel();
        txt_apellidos_clientes = new javax.swing.JTextField();
        lbl_direccion_clientes = new javax.swing.JLabel();
        txt_direccion_clientes = new javax.swing.JTextField();
        lbl_telefono_clientes = new javax.swing.JLabel();
        txt_telefono_clientes = new javax.swing.JTextField();
        lbl_fn_clientes = new javax.swing.JLabel();
        txt_fn_clientes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_datos_clientes = new javax.swing.JTable();
        lbl_id_clientes = new javax.swing.JLabel();
        lbl_resultado_id_clientes = new javax.swing.JLabel();
        bt_agregar_clientes = new javax.swing.JButton();
        bt_actualizar_clientes = new javax.swing.JButton();
        bt_eliminar_clientes = new javax.swing.JButton();
        jp_empleados = new javax.swing.JPanel();
        lbl_titulo1 = new javax.swing.JLabel();
        lbl_codigo_empleados = new javax.swing.JLabel();
        lbl_nombres_empleados = new javax.swing.JLabel();
        lbl_apellidos_empleados = new javax.swing.JLabel();
        lbl_direccion_empleados = new javax.swing.JLabel();
        lbl_telefono_empleados = new javax.swing.JLabel();
        lbl_fn_empleados = new javax.swing.JLabel();
        txt_codigo_empleados = new javax.swing.JTextField();
        txt_nombres_empleados = new javax.swing.JTextField();
        txt_apellidos_empleados = new javax.swing.JTextField();
        txt_direccion_empleados = new javax.swing.JTextField();
        txt_telefono_empleados = new javax.swing.JTextField();
        txt_fn_empleados = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_datos_empleados = new javax.swing.JTable();
        lbl_id_empleados = new javax.swing.JLabel();
        lbl_resultado_id_empleados = new javax.swing.JLabel();
        lbl_puestos_empleados = new javax.swing.JLabel();
        cb_puestos = new javax.swing.JComboBox<>();
        bt_agregar_empleados = new javax.swing.JButton();
        bt_actualizar_empleados = new javax.swing.JButton();
        bt_eliminar_empleados = new javax.swing.JButton();
        jp_puestos = new javax.swing.JPanel();
        lbl_titulo2 = new javax.swing.JLabel();
        lbl_nombres_puestos = new javax.swing.JLabel();
        txt_puestos = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_datos_puestos = new javax.swing.JTable();
        lbl_id_puestos = new javax.swing.JLabel();
        lbl_resultado_id_puestos = new javax.swing.JLabel();
        bt_eliminar_puestos = new javax.swing.JButton();
        bt_actualizar_puestos = new javax.swing.JButton();
        bt_agregar_puestos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_titulo.setText("FORMULARIO CLIENTES");

        lbl_nit_clientes.setText("NIT");

        lbl_nombres_clientes.setText("NOMBRES");

        lbl_apellidos_clientes.setText("APELLIDOS");

        lbl_direccion_clientes.setText("DIRECCIÓN");

        lbl_telefono_clientes.setText("TELEFONO");

        lbl_fn_clientes.setText("FECHA NACIMIENTO");

        tbl_datos_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_datos_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_datos_clientesMouseClicked(evt);
            }
        });
        tbl_datos_clientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_datos_clientesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_datos_clientes);

        lbl_id_clientes.setText("ID");

        lbl_resultado_id_clientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bt_agregar_clientes.setText("AGREGAR");
        bt_agregar_clientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_agregar_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregar_clientesActionPerformed(evt);
            }
        });

        bt_actualizar_clientes.setText("ACTUALIZAR");
        bt_actualizar_clientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_actualizar_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_actualizar_clientesActionPerformed(evt);
            }
        });

        bt_eliminar_clientes.setText("ELIMINAR");
        bt_eliminar_clientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_eliminar_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminar_clientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_clientesLayout = new javax.swing.GroupLayout(jp_clientes);
        jp_clientes.setLayout(jp_clientesLayout);
        jp_clientesLayout.setHorizontalGroup(
            jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_clientesLayout.createSequentialGroup()
                .addGroup(jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_clientesLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_clientesLayout.createSequentialGroup()
                                .addComponent(lbl_fn_clientes)
                                .addGap(18, 18, 18)
                                .addComponent(txt_fn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_clientesLayout.createSequentialGroup()
                                .addGroup(jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_nit_clientes)
                                    .addComponent(lbl_nombres_clientes)
                                    .addComponent(lbl_id_clientes))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nombres_clientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nit_clientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_resultado_id_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_clientesLayout.createSequentialGroup()
                                .addComponent(lbl_apellidos_clientes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_apellidos_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_clientesLayout.createSequentialGroup()
                                .addGroup(jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_direccion_clientes)
                                    .addComponent(lbl_telefono_clientes))
                                .addGap(69, 69, 69)
                                .addGroup(jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_telefono_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_direccion_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_actualizar_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_agregar_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_eliminar_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(302, 302, 302))
                    .addGroup(jp_clientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(jp_clientesLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(lbl_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_clientesLayout.setVerticalGroup(
            jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_resultado_id_clientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id_clientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_clientesLayout.createSequentialGroup()
                        .addGroup(jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nit_clientes)
                            .addComponent(txt_nit_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombres_clientes)
                            .addComponent(txt_nombres_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_apellidos_clientes)
                            .addComponent(txt_apellidos_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_clientesLayout.createSequentialGroup()
                        .addComponent(bt_agregar_clientes)
                        .addGap(18, 18, 18)
                        .addComponent(bt_actualizar_clientes)
                        .addGap(18, 18, 18)
                        .addComponent(bt_eliminar_clientes)))
                .addGap(18, 18, 18)
                .addGroup(jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_direccion_clientes)
                    .addComponent(txt_direccion_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefono_clientes)
                    .addComponent(txt_telefono_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fn_clientes)
                    .addComponent(txt_fn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jp_principal.addTab("CLIENTES", jp_clientes);

        lbl_titulo1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_titulo1.setText("FORMULARIO EMPLEADOS");

        lbl_codigo_empleados.setText("CODIGO");

        lbl_nombres_empleados.setText("NOMBRES");

        lbl_apellidos_empleados.setText("APELLIDOS");

        lbl_direccion_empleados.setText("DIRECCIÓN");

        lbl_telefono_empleados.setText("TELEFONO");

        lbl_fn_empleados.setText("FECHA NACIMIENTO");

        tbl_datos_empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_datos_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_datos_empleadosMouseClicked(evt);
            }
        });
        tbl_datos_empleados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_datos_empleadosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_datos_empleados);

        lbl_id_empleados.setText("ID");

        lbl_resultado_id_empleados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_puestos_empleados.setText("PUESTOS");

        bt_agregar_empleados.setText("AGREGAR");
        bt_agregar_empleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_agregar_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregar_empleadosActionPerformed(evt);
            }
        });

        bt_actualizar_empleados.setText("ACTUALIZAR");
        bt_actualizar_empleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_actualizar_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_actualizar_empleadosActionPerformed(evt);
            }
        });

        bt_eliminar_empleados.setText("ELIMINAR");
        bt_eliminar_empleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_eliminar_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminar_empleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_empleadosLayout = new javax.swing.GroupLayout(jp_empleados);
        jp_empleados.setLayout(jp_empleadosLayout);
        jp_empleadosLayout.setHorizontalGroup(
            jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_empleadosLayout.createSequentialGroup()
                .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_empleadosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_empleadosLayout.createSequentialGroup()
                                .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_codigo_empleados)
                                    .addComponent(lbl_nombres_empleados)
                                    .addComponent(lbl_id_empleados))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nombres_empleados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_codigo_empleados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_resultado_id_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_empleadosLayout.createSequentialGroup()
                                .addComponent(lbl_apellidos_empleados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_apellidos_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_empleadosLayout.createSequentialGroup()
                                .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_direccion_empleados)
                                    .addComponent(lbl_telefono_empleados))
                                .addGap(69, 69, 69)
                                .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_telefono_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_direccion_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_empleadosLayout.createSequentialGroup()
                                .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_fn_empleados)
                                    .addComponent(lbl_puestos_empleados))
                                .addGap(18, 18, 18)
                                .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_fn_empleados, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(cb_puestos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(80, 80, 80)
                        .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_actualizar_empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_agregar_empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_eliminar_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 308, Short.MAX_VALUE))
                    .addGroup(jp_empleadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(jp_empleadosLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(lbl_titulo1)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jp_empleadosLayout.setVerticalGroup(
            jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_empleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_resultado_id_empleados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id_empleados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_empleadosLayout.createSequentialGroup()
                        .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_codigo_empleados)
                            .addComponent(txt_codigo_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_agregar_empleados))
                        .addGap(18, 18, 18)
                        .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombres_empleados)
                            .addComponent(txt_nombres_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_actualizar_empleados))
                        .addGap(18, 18, 18)
                        .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_apellidos_empleados)
                            .addComponent(txt_apellidos_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_eliminar_empleados))
                        .addGap(18, 18, 18)
                        .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_direccion_empleados)
                            .addComponent(txt_direccion_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_telefono_empleados)
                            .addComponent(txt_telefono_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_fn_empleados)
                            .addComponent(txt_fn_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_puestos_empleados))
                    .addComponent(cb_puestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jp_principal.addTab("EMPLEADOS", jp_empleados);

        lbl_titulo2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_titulo2.setText("FORMULARIO PUESTOS");

        lbl_nombres_puestos.setText("NOMBRE DEL PUESTO");

        tbl_datos_puestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_datos_puestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_datos_puestosMouseClicked(evt);
            }
        });
        tbl_datos_puestos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_datos_puestosKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_datos_puestos);

        lbl_id_puestos.setText("ID");

        lbl_resultado_id_puestos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bt_eliminar_puestos.setText("ELIMINAR");
        bt_eliminar_puestos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_eliminar_puestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminar_puestosActionPerformed(evt);
            }
        });

        bt_actualizar_puestos.setText("ACTUALIZAR");
        bt_actualizar_puestos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_actualizar_puestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_actualizar_puestosActionPerformed(evt);
            }
        });

        bt_agregar_puestos.setText("AGREGAR");
        bt_agregar_puestos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_agregar_puestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregar_puestosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_puestosLayout = new javax.swing.GroupLayout(jp_puestos);
        jp_puestos.setLayout(jp_puestosLayout);
        jp_puestosLayout.setHorizontalGroup(
            jp_puestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_puestosLayout.createSequentialGroup()
                .addGroup(jp_puestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_puestosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jp_puestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombres_puestos)
                            .addComponent(lbl_id_puestos))
                        .addGap(32, 32, 32)
                        .addGroup(jp_puestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_resultado_id_puestos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_puestos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jp_puestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_actualizar_puestos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_agregar_puestos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_eliminar_puestos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jp_puestosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
            .addGroup(jp_puestosLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(lbl_titulo2)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        jp_puestosLayout.setVerticalGroup(
            jp_puestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_puestosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo2)
                .addGap(34, 34, 34)
                .addGroup(jp_puestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_agregar_puestos)
                    .addGroup(jp_puestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_resultado_id_puestos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_id_puestos)))
                .addGap(18, 18, 18)
                .addGroup(jp_puestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_actualizar_puestos)
                    .addComponent(lbl_nombres_puestos)
                    .addComponent(txt_puestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_eliminar_puestos)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jp_principal.addTab("PUESTOS", jp_puestos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_principal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_agregar_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregar_clientesActionPerformed
        // TODO add your handling code here:
        cliente = new Cliente(0,txt_nit_clientes.getText(), txt_nombres_clientes.getText(), txt_apellidos_clientes.getText(), txt_direccion_clientes.getText(), txt_telefono_clientes.getText(), this.txt_fn_clientes.getText());
        
        cliente.agregar();
        tbl_datos_clientes.setModel(cliente.leer());
        limpia_datos_clientes();
    }//GEN-LAST:event_bt_agregar_clientesActionPerformed

    private void bt_actualizar_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_actualizar_clientesActionPerformed
        // TODO add your handling code here:
        cliente = new Cliente(Integer.valueOf(lbl_resultado_id_clientes.getText()), txt_nit_clientes.getText(), txt_nombres_clientes.getText(), txt_apellidos_clientes.getText(), txt_direccion_clientes.getText(), txt_telefono_clientes.getText(), this.txt_fn_clientes.getText());
        cliente.actualizar();
        tbl_datos_clientes.setModel(cliente.leer());
        limpia_datos_clientes();
    }//GEN-LAST:event_bt_actualizar_clientesActionPerformed

    private void bt_eliminar_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminar_clientesActionPerformed
        // TODO add your handling code here:
        cliente = new Cliente();
        cliente.setId(Integer.valueOf(lbl_resultado_id_clientes.getText()));
        cliente.borrar();
        tbl_datos_clientes.setModel(cliente.leer());
        limpia_datos_clientes();
    }//GEN-LAST:event_bt_eliminar_clientesActionPerformed

    private void tbl_datos_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_datos_clientesMouseClicked
        // TODO add your handling code here:
        select_datos_clientes();
    }//GEN-LAST:event_tbl_datos_clientesMouseClicked

    private void tbl_datos_clientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_datos_clientesKeyReleased
        // TODO add your handling code here:
        select_datos_clientes();
    }//GEN-LAST:event_tbl_datos_clientesKeyReleased

    private void bt_agregar_puestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregar_puestosActionPerformed
        // TODO add your handling code here:
        puesto = new Puesto(0, txt_puestos.getText());
        puesto.agregarPuesto();
        tbl_datos_puestos.setModel(puesto.leerPuestos());
        limpia_datos_puestos();
    }//GEN-LAST:event_bt_agregar_puestosActionPerformed

    private void bt_actualizar_puestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_actualizar_puestosActionPerformed
        // TODO add your handling code here:
        puesto = new Puesto(Integer.parseInt(lbl_resultado_id_puestos.getText()), txt_puestos.getText());
        puesto.actualizar();
        tbl_datos_puestos.setModel(puesto.leerPuestos());
        limpia_datos_puestos();
    }//GEN-LAST:event_bt_actualizar_puestosActionPerformed

    private void bt_eliminar_puestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminar_puestosActionPerformed
        // TODO add your handling code here:
        puesto.setIdPuesto(Integer.parseInt(lbl_resultado_id_puestos.getText()));
        puesto.borrar();
        tbl_datos_puestos.setModel(puesto.leerPuestos());
        limpia_datos_puestos();
    }//GEN-LAST:event_bt_eliminar_puestosActionPerformed

    private void tbl_datos_puestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_datos_puestosMouseClicked
        // TODO add your handling code here:
        select_datos_puestos();
    }//GEN-LAST:event_tbl_datos_puestosMouseClicked

    private void tbl_datos_puestosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_datos_puestosKeyReleased
        // TODO add your handling code here:
        select_datos_puestos();
    }//GEN-LAST:event_tbl_datos_puestosKeyReleased
    
    private void bt_agregar_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregar_empleadosActionPerformed
        // TODO add your handling code here:
        // Obtener el índice del puesto seleccionado en el ComboBox
        int puesto = cb_puestos.getSelectedIndex();
        if (puesto == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un puesto válido.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }      
        empleado = new Empleado(0, this.txt_codigo_empleados.getText(), this.txt_nombres_empleados.getText(), this.txt_apellidos_empleados.getText(),this.txt_direccion_empleados.getText(), this.txt_telefono_empleados.getText(), this.txt_fn_empleados.getText(), puesto);
        empleado.agregar();
        tbl_datos_empleados.setModel(empleado.leer());
        limpia_datos_empleados();
    }//GEN-LAST:event_bt_agregar_empleadosActionPerformed

    private void bt_actualizar_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_actualizar_empleadosActionPerformed
        // TODO add your handling code here:
        if (lbl_resultado_id_empleados.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un empleado para actualizar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int puesto = cb_puestos.getSelectedIndex();
        empleado = new Empleado(Integer.parseInt(lbl_resultado_id_empleados.getText()), txt_nombres_empleados.getText(), txt_codigo_empleados.getText(), txt_apellidos_empleados.getText(), txt_direccion_empleados.getText(), txt_telefono_empleados.getText(), txt_fn_empleados.getText(), puesto);
        empleado.actualizar();
        tbl_datos_empleados.setModel(empleado.leer());
        limpia_datos_empleados();
    }//GEN-LAST:event_bt_actualizar_empleadosActionPerformed

    private void bt_eliminar_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminar_empleadosActionPerformed
        // TODO add your handling code here:
        if (lbl_resultado_id_empleados.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un empleado para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int id = Integer.parseInt(lbl_resultado_id_empleados.getText());
        empleado = new Empleado();
        empleado.setId(id);
        empleado.borrar();
        tbl_datos_empleados.setModel(empleado.leer());
        limpia_datos_empleados();
    }//GEN-LAST:event_bt_eliminar_empleadosActionPerformed

    private void tbl_datos_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_datos_empleadosMouseClicked
        // TODO add your handling code here:
        select_datos_empleados();
    }//GEN-LAST:event_tbl_datos_empleadosMouseClicked

    private void tbl_datos_empleadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_datos_empleadosKeyReleased
        // TODO add your handling code here:
        select_datos_empleados();
    }//GEN-LAST:event_tbl_datos_empleadosKeyReleased
     
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_actualizar_clientes;
    private javax.swing.JButton bt_actualizar_empleados;
    private javax.swing.JButton bt_actualizar_puestos;
    private javax.swing.JButton bt_agregar_clientes;
    private javax.swing.JButton bt_agregar_empleados;
    private javax.swing.JButton bt_agregar_puestos;
    private javax.swing.JButton bt_eliminar_clientes;
    private javax.swing.JButton bt_eliminar_empleados;
    private javax.swing.JButton bt_eliminar_puestos;
    private javax.swing.JComboBox<String> cb_puestos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jp_clientes;
    private javax.swing.JPanel jp_empleados;
    private javax.swing.JTabbedPane jp_principal;
    private javax.swing.JPanel jp_puestos;
    private javax.swing.JLabel lbl_apellidos_clientes;
    private javax.swing.JLabel lbl_apellidos_empleados;
    private javax.swing.JLabel lbl_codigo_empleados;
    private javax.swing.JLabel lbl_direccion_clientes;
    private javax.swing.JLabel lbl_direccion_empleados;
    private javax.swing.JLabel lbl_fn_clientes;
    private javax.swing.JLabel lbl_fn_empleados;
    private javax.swing.JLabel lbl_id_clientes;
    private javax.swing.JLabel lbl_id_empleados;
    private javax.swing.JLabel lbl_id_puestos;
    private javax.swing.JLabel lbl_nit_clientes;
    private javax.swing.JLabel lbl_nombres_clientes;
    private javax.swing.JLabel lbl_nombres_empleados;
    private javax.swing.JLabel lbl_nombres_puestos;
    private javax.swing.JLabel lbl_puestos_empleados;
    private javax.swing.JLabel lbl_resultado_id_clientes;
    private javax.swing.JLabel lbl_resultado_id_empleados;
    private javax.swing.JLabel lbl_resultado_id_puestos;
    private javax.swing.JLabel lbl_telefono_clientes;
    private javax.swing.JLabel lbl_telefono_empleados;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_titulo1;
    private javax.swing.JLabel lbl_titulo2;
    private javax.swing.JTable tbl_datos_clientes;
    private javax.swing.JTable tbl_datos_empleados;
    private javax.swing.JTable tbl_datos_puestos;
    private javax.swing.JTextField txt_apellidos_clientes;
    private javax.swing.JTextField txt_apellidos_empleados;
    private javax.swing.JTextField txt_codigo_empleados;
    private javax.swing.JTextField txt_direccion_clientes;
    private javax.swing.JTextField txt_direccion_empleados;
    private javax.swing.JTextField txt_fn_clientes;
    private javax.swing.JTextField txt_fn_empleados;
    private javax.swing.JTextField txt_nit_clientes;
    private javax.swing.JTextField txt_nombres_clientes;
    private javax.swing.JTextField txt_nombres_empleados;
    private javax.swing.JTextField txt_puestos;
    private javax.swing.JTextField txt_telefono_clientes;
    private javax.swing.JTextField txt_telefono_empleados;
    // End of variables declaration//GEN-END:variables
}
